# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fastx.grpc.user.v1 import user_pb2 as fastx_dot_grpc_dot_user_dot_v1_dot_user__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fastx/grpc/user/v1/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchUser = channel.unary_unary(
                '/fastx.grpc.user.v1.UserService/FetchUser',
                request_serializer=fastx_dot_grpc_dot_user_dot_v1_dot_user__pb2.FetchUserRequest.SerializeToString,
                response_deserializer=fastx_dot_grpc_dot_user_dot_v1_dot_user__pb2.FetchUserResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchUser': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchUser,
                    request_deserializer=fastx_dot_grpc_dot_user_dot_v1_dot_user__pb2.FetchUserRequest.FromString,
                    response_serializer=fastx_dot_grpc_dot_user_dot_v1_dot_user__pb2.FetchUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fastx.grpc.user.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fastx.grpc.user.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fastx.grpc.user.v1.UserService/FetchUser',
            fastx_dot_grpc_dot_user_dot_v1_dot_user__pb2.FetchUserRequest.SerializeToString,
            fastx_dot_grpc_dot_user_dot_v1_dot_user__pb2.FetchUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
