# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fastx/grpc/health/v1/health.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fastx/grpc/health/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!fastx/grpc/health/v1/health.proto\x12\x14\x66\x61stx.grpc.health.v1\" \n\rHealthRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"L\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x19\n\x11timestamp_unix_ms\x18\x02 \x01(\x03\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t2c\n\rHealthService\x12R\n\x05\x43heck\x12#.fastx.grpc.health.v1.HealthRequest\x1a$.fastx.grpc.health.v1.HealthResponseB\x16Z\x14\x66\x61stx/grpc/health/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fastx.grpc.health.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024fastx/grpc/health/v1'
  _globals['_HEALTHREQUEST']._serialized_start=59
  _globals['_HEALTHREQUEST']._serialized_end=91
  _globals['_HEALTHRESPONSE']._serialized_start=93
  _globals['_HEALTHRESPONSE']._serialized_end=169
  _globals['_HEALTHSERVICE']._serialized_start=171
  _globals['_HEALTHSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
