"""Message queues / DLQ — re-exported from ``fast_queues``. Prefer ``from fast_queues import …`` in new code."""

from fast_queues import (
    DEFAULT_DLQ_SUFFIX,
    DEFAULT_QUARANTINE_SUFFIX,
    DELAY_SECONDS_KEY,
    ENVELOPE_VERSION_KEY,
    FAILURE_COUNT_KEY,
    IQueueBackend,
    LAST_ERROR_KEY,
    PAYLOAD_KEY,
    PRIORITY_KEY,
    QueueBroker,
    QueueMessage,
    QueueMessageEnvelope,
    QueuesConfiguration,
    QueuesConfigurationDTO,
    dlq_name,
    is_dlq_name,
    is_quarantine_name,
    prepare_dlq_message,
    prepare_quarantine_message,
    primary_queue_from_dlq,
    primary_queue_from_quarantine,
    quarantine_name,
    should_quarantine,
)

__all__ = [
    "DEFAULT_DLQ_SUFFIX",
    "DEFAULT_QUARANTINE_SUFFIX",
    "DELAY_SECONDS_KEY",
    "ENVELOPE_VERSION_KEY",
    "FAILURE_COUNT_KEY",
    "IQueueBackend",
    "LAST_ERROR_KEY",
    "PAYLOAD_KEY",
    "PRIORITY_KEY",
    "QueueBroker",
    "QueueMessage",
    "QueueMessageEnvelope",
    "QueuesConfiguration",
    "QueuesConfigurationDTO",
    "dlq_name",
    "is_dlq_name",
    "is_quarantine_name",
    "prepare_dlq_message",
    "prepare_quarantine_message",
    "primary_queue_from_dlq",
    "primary_queue_from_quarantine",
    "quarantine_name",
    "should_quarantine",
]
