# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fastmvc/grpc/health/v1/health.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fastmvc/grpc/health/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#fastmvc/grpc/health/v1/health.proto\x12\x16\x66\x61stmvc.grpc.health.v1\" \n\rHealthRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"L\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x19\n\x11timestamp_unix_ms\x18\x02 \x01(\x03\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t2g\n\rHealthService\x12V\n\x05\x43heck\x12%.fastmvc.grpc.health.v1.HealthRequest\x1a&.fastmvc.grpc.health.v1.HealthResponseB\x18Z\x16\x66\x61stmvc/grpc/health/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fastmvc.grpc.health.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026fastmvc/grpc/health/v1'
  _globals['_HEALTHREQUEST']._serialized_start=63
  _globals['_HEALTHREQUEST']._serialized_end=95
  _globals['_HEALTHRESPONSE']._serialized_start=97
  _globals['_HEALTHRESPONSE']._serialized_end=173
  _globals['_HEALTHSERVICE']._serialized_start=175
  _globals['_HEALTHSERVICE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
