# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fastmvc/grpc/user/v1/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fastmvc/grpc/user/v1/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x66\x61stmvc/grpc/user/v1/user.proto\x12\x14\x66\x61stmvc.grpc.user.v1\"5\n\x10\x46\x65tchUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"@\n\x11\x46\x65tchUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2k\n\x0bUserService\x12\\\n\tFetchUser\x12&.fastmvc.grpc.user.v1.FetchUserRequest\x1a\'.fastmvc.grpc.user.v1.FetchUserResponseB\x16Z\x14\x66\x61stmvc/grpc/user/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fastmvc.grpc.user.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024fastmvc/grpc/user/v1'
  _globals['_FETCHUSERREQUEST']._serialized_start=57
  _globals['_FETCHUSERREQUEST']._serialized_end=110
  _globals['_FETCHUSERRESPONSE']._serialized_start=112
  _globals['_FETCHUSERRESPONSE']._serialized_end=176
  _globals['_USERSERVICE']._serialized_start=178
  _globals['_USERSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
